AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Amazon ElasticSearch cluster set-up

  SAM Template for creating a new Amazon ElasticSearch cluster in a new VPC with the given instance sizes and nodes.

Parameters:
  DomainName:
    Description: The Elasticsearch Domain name
    Type: String
    Default: elasticsearch-domain-xyz

  VPC:
    Description: The VPC we will use.
    Type: AWS::EC2::VPC::Id

  PublicSubnet1:
    Description: The public subnet 1.
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2:
    Description: The public subnet 2.
    Type: AWS::EC2::Subnet::Id

  ElasticsearchVersion:
    Description: The Elasticsearch Version
    Type: String
    Default: 7.1
    AllowedValues: 
      - 7.1
      - 6.8
      - 5.6
      - 2.3
      - 1.5
  
  InstanceType:
    Description: The data instance type
    Type: String
    Default: m5.large.elasticsearch
    AllowedValues: 
      - c5.large.elasticsearch
      - c5.xlarge.elasticsearch
      - c5.2xlarge.elasticsearch
      - c5.4xlarge.elasticsearch
      - c5.9xlarge.elasticsearch
      - c5.18xlarge.elasticsearch
      - i3.large.elasticsearch
      - i3.xlarge.elasticsearch
      - i3.2xlarge.elasticsearch
      - i3.4xlarge.elasticsearch
      - i3.8xlarge.elasticsearch
      - i3.16xlarge.elasticsearch
      - m5.large.elasticsearch
      - m5.xlarge.elasticsearch
      - m5.2xlarge.elasticsearch
      - m5.4xlarge.elasticsearch
      - m5.12xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
      - r5.2xlarge.elasticsearch
      - r5.4xlarge.elasticsearch
      - r5.12xlarge.elasticsearch
      - t2.small.elasticsearch
      - t2.medium.elasticsearch

  InstanceCount:
    Type: String
    Default: 2

  DedicatedMasterInstanceType:
    Description: The dedicated master instance type
    Type: String
    Default: m5.large.elasticsearch
    AllowedValues: 
      - c5.large.elasticsearch
      - c5.xlarge.elasticsearch
      - c5.2xlarge.elasticsearch
      - c5.4xlarge.elasticsearch
      - c5.9xlarge.elasticsearch
      - c5.18xlarge.elasticsearch
      - i3.large.elasticsearch
      - i3.xlarge.elasticsearch
      - i3.2xlarge.elasticsearch
      - i3.4xlarge.elasticsearch
      - i3.8xlarge.elasticsearch
      - i3.16xlarge.elasticsearch
      - m5.large.elasticsearch
      - m5.xlarge.elasticsearch
      - m5.2xlarge.elasticsearch
      - m5.4xlarge.elasticsearch
      - m5.12xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
      - r5.2xlarge.elasticsearch
      - r5.4xlarge.elasticsearch
      - r5.12xlarge.elasticsearch
      - t2.small.elasticsearch
      - t2.medium.elasticsearch

  DedicatedMasterInstanceCount:
    Type: String
    Default: 3
    AllowedValues: 
      - 3
      - 5

  VPC:
    Description: The VPC into which the ES cluster will be deployed.
    Type: AWS::EC2::VPC::Id

  PublicSubnet1:
    Description: The first subnet into which the ES cluster will be deployed.
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2:
    Description: The first subnet into which the ES cluster will be deployed.
    Type: AWS::EC2::Subnet::Id

Resources:
  AWSServiceRoleForAmazonElasticsearchService:
    Type: AWS::IAM::ServiceLinkedRole
    Properties: 
      AWSServiceName: es.amazonaws.com

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Limits security group ingress and egress traffic for the ES cluster
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443

  # to run a 3 AZ cluster: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/8
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html
    Properties:
      DomainName: !Sub "${DomainName}-${AWS::StackName}"
      ElasticsearchVersion: !Ref ElasticsearchVersion
      NodeToNodeEncryptionOptions: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-nodetonodeencryptionoptions.html
        Enabled: true
      EncryptionAtRestOptions: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-encryptionatrestoptions.html
        Enabled: true
      ElasticsearchClusterConfig: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html
        DedicatedMasterEnabled: true
        ZoneAwarenessEnabled: true
        InstanceCount: !Ref InstanceCount
        InstanceType: !Ref InstanceType
        DedicatedMasterType: !Ref DedicatedMasterInstanceType
        DedicatedMasterCount: !Ref DedicatedMasterInstanceCount
      EBSOptions: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-ebsoptions.html
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-snapshotoptions.html
        AutomatedSnapshotStartHour: 0
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*'
      AdvancedOptions: # https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-advanced-options
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-vpcoptions.html
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
      Tags: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
      - Key: Name
        Value: !Sub "${AWS::StackName}:ElasticsearchDomain"

  ElasticsearchDomainEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/DEV/ES-WORKSHOP/ES-CLUSTER-ENDPOINT-${AWS::StackName}"
      Type: String
      Value: !Sub "https://${ElasticsearchDomain.DomainEndpoint}"
      Tags:
        "Environment": "DEV"

Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
  DomainEndpoint:
    Value: !Sub "https://${ElasticsearchDomain.DomainEndpoint}"
  SSMElasticsearchDomainEndpointParameter:
    Value: !Sub "/DEV/ES-WORKSHOP/ES-CLUSTER-ENDPOINT-${AWS::StackName}"